### ISSUE TITLE
Serve each experiment on its own port

### ISSUE THREAD

**Issue by iezer** [chancancode/ember-bench#1]
- All served from a single Puma instance by adding multiple `-p` options in `bin/serve`
- specified for each experiment in `config/experiments.json`
- used to determine folder in default `server.ru

**Comment by chancancode** [comment]
:+1:
- get rid of the "merging" step
- probably don't need to specify the ports manually, seems like it's just busywork that could be avoided; we could just auto-increment from 9292 or similar, and pass them to `bin/serve` and `test.ts` as arguments
